const data = [
  {
    num: 'https://i.ibb.co/9tDzVzF/1.png',
    name: 'Большой шар с рисунком',
    count: '2',
    year: '1960',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 1
  },
  {
    num: 'https://i.ibb.co/LrTJVPc/2.png',
    name: 'Зелёный шар с цветами',
    count: '5',
    year: '2000',
    shape: 'шар',
    color: 'зелёный',
    size: 'большой',
    favorite: false,
    id: 2
  },
  {
    num: 'https://i.ibb.co/7g0gKHw/3.png',
    name: 'Красный матовый шар',
    count: '3',
    year: '1990',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 3
  },
  {
    num: 'https://i.ibb.co/xz94nVK/4.png',
    name: 'Сосулька красная',
    count: '2',
    year: '1980',
    shape: 'фигурка',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 4
  },
  {
    num: 'https://i.ibb.co/7bgjJdb/5.png',
    name: 'Красный виноград',
    count: '4',
    year: '1980',
    shape: 'фигурка',
    color: 'красный',
    size: 'средний',
    favorite: true,
    id: 5
  },
  {
    num: 'https://i.ibb.co/Dw5xjv3/6.png',
    name: 'Красный шар с рисунком',
    count: '6',
    year: '2010',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 6
  },
  {
    num: 'https://i.ibb.co/qnZcwwk/7.png',
    name: 'Молочно-белый шар',
    count: '12',
    year: '1960',
    shape: 'шар',
    color: 'белый',
    size: 'средний',
    favorite: true,
    id: 7
  },
  {
    num: 'https://i.ibb.co/QNC7sgD/8.png',
    name: 'Красный шар',
    count: '10',
    year: '2010',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 8
  },
  {
    num: 'https://i.ibb.co/vzdtYN7/9.png',
    name: 'Колокольчик старинный',
    count: '2',
    year: '1950',
    shape: 'колокольчик',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 9
  },
  {
    num: 'https://i.ibb.co/jk3vq1C/10.png',
    name: 'Белый шар ретро',
    count: '7',
    year: '1960',
    shape: 'шар',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 10
  },
  {
    num: 'https://i.ibb.co/mHKKzYq/11.png',
    name: 'Шишка еловая белая',
    count: '11',
    year: '1960',
    shape: 'шишка',
    color: 'белый',
    size: 'малый',
    favorite: false,
    id: 11
  },
  {
    num: 'https://i.ibb.co/jVmxTpP/12.png',
    name: 'Белый шар с цветами',
    count: '5',
    year: '1980',
    shape: 'шар',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 12
  },
  {
    num: 'https://i.ibb.co/wLDt6rP/13.png',
    name: 'Шар расписной Река',
    count: '3',
    year: '1970',
    shape: 'шар',
    color: 'синий',
    size: 'большой',
    favorite: true,
    id: 13
  },
  {
    num: 'https://i.ibb.co/hCHyRSk/14.png',
    name: 'Шар расписной Деревня',
    count: '4',
    year: '1970',
    shape: 'шар',
    color: 'синий',
    size: 'большой',
    favorite: true,
    id: 14
  },
  {
    num: 'https://i.ibb.co/BnJyCTb/15.png',
    name: 'Колокольчик расписной',
    count: '3',
    year: '1970',
    shape: 'колокольчик',
    color: 'синий',
    size: 'средний',
    favorite: false,
    id: 15
  },
  {
    num: 'https://i.ibb.co/MRky1x0/16.png',
    name: 'Шишка расписная Пейзаж',
    count: '3',
    year: '1970',
    shape: 'шишка',
    color: 'синий',
    size: 'средний',
    favorite: true,
    id: 16
  },
  {
    num: 'https://i.ibb.co/0nPNm7Y/17.png',
    name: 'Шишка расписная',
    count: '7',
    year: '1970',
    shape: 'шишка',
    color: 'красный',
    size: 'средний',
    favorite: false,
    id: 17
  },
  {
    num: 'https://i.ibb.co/3cPBgYn/18.png',
    name: 'Желтый шар с бантом',
    count: '2',
    year: '2010',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 18
  },
  {
    num: 'https://i.ibb.co/PDJhmGM/19.png',
    name: 'Желтый шар с паетками',
    count: '12',
    year: '1980',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 19
  },
  {
    num: 'https://i.ibb.co/VLGFWJT/20.png',
    name: 'Красный шар с бантом',
    count: '8',
    year: '1950',
    shape: 'шар',
    color: 'красный',
    size: 'средний',
    favorite: true,
    id: 20
  },
  {
    num: 'https://i.ibb.co/HHh6Sf1/21.png',
    name: 'Красный шар с звёздами',
    count: '4',
    year: '1970',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: true,
    id: 21
  },
  {
    num: 'https://i.ibb.co/Npm7P8n/22.png',
    name: 'Шишка еловая золотая',
    count: '11',
    year: '1990',
    shape: 'шишка',
    color: 'желтый',
    size: 'малый',
    favorite: false,
    id: 22
  },
  {
    num: 'https://i.ibb.co/k5mfNTR/23.png',
    name: 'Колокольчик старинный',
    count: '9',
    year: '1950',
    shape: 'колокольчик',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 23
  },
  {
    num: 'https://i.ibb.co/xhv4y47/24.png',
    name: 'Снежинка изящная',
    count: '1',
    year: '1940',
    shape: 'снежинка',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 24
  },
  {
    num: 'https://i.ibb.co/ThSMh3G/25.png',
    name: 'Розовый шар с блёстками',
    count: '12',
    year: '2010',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 25
  },
  {
    num: 'https://i.ibb.co/2vdKm31/26.png',
    name: 'Рубиново-золотой шар',
    count: '8',
    year: '1960',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 26
  },
  {
    num: 'https://i.ibb.co/6Ptnqcv/27.png',
    name: 'Красный шар с узором',
    count: '4',
    year: '2010',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 27
  },
  {
    num: 'https://i.ibb.co/cJLGL5J/28.png',
    name: 'Бордовый шар с узором',
    count: '10',
    year: '2010',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 28
  },
  {
    num: 'https://i.ibb.co/vx0y73c/29.png',
    name: 'Старинный шар с цветами',
    count: '5',
    year: '1950',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: true,
    id: 29
  },
  {
    num: 'https://i.ibb.co/5RyyLgn/30.png',
    name: 'Старинный шар с узором',
    count: '8',
    year: '1950',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: true,
    id: 30
  },
  {
    num: 'https://i.ibb.co/BcG07GS/31.png',
    name: 'Красный шар с блёстками',
    count: '8',
    year: '2010',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 31
  },
  {
    num: 'https://i.ibb.co/FV60n5K/32.png',
    name: 'Синий шар Вселенная',
    count: '11',
    year: '1970',
    shape: 'шар',
    color: 'синий',
    size: 'большой',
    favorite: false,
    id: 32
  },
  {
    num: 'https://i.ibb.co/cwDbtBP/33.png',
    name: 'Синий шар со снежинкой',
    count: '6',
    year: '2010',
    shape: 'шар',
    color: 'синий',
    size: 'средний',
    favorite: false,
    id: 33
  },
  {
    num: 'https://i.ibb.co/Z6kPbZy/34.png',
    name: 'Зелёный  шар с узором',
    count: '8',
    year: '2010',
    shape: 'шар',
    color: 'зелёный',
    size: 'большой',
    favorite: false,
    id: 34
  },
  {
    num: 'https://i.ibb.co/s2XC84x/35.png',
    name: 'Фигурка Лис в шарфе',
    count: '8',
    year: '1950',
    shape: 'фигурка',
    color: 'желтый',
    size: 'средний',
    favorite: true,
    id: 35
  },
  {
    num: 'https://i.ibb.co/vP1QzM7/36.png',
    name: 'Сиреневый шар Метель',
    count: '1',
    year: '2000',
    shape: 'шар',
    color: 'синий',
    size: 'большой',
    favorite: false,
    id: 36
  },
  {
    num: 'https://i.ibb.co/4R1L6yL/37.png',
    name: 'Зелёный  шар Метель',
    count: '6',
    year: '2000',
    shape: 'шар',
    color: 'зелёный',
    size: 'большой',
    favorite: false,
    id: 37
  },
  {
    num: 'https://i.ibb.co/yQFzCrD/38.png',
    name: 'Голубой  шар Метель',
    count: '6',
    year: '2000',
    shape: 'шар',
    color: 'синий',
    size: 'большой',
    favorite: false,
    id: 38
  },
  {
    num: 'https://i.ibb.co/tX5GkMf/39.png',
    name: 'Красная снежинка',
    count: '6',
    year: '1990',
    shape: 'снежинка',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 39
  },
  {
    num: 'https://i.ibb.co/dBtqBTK/40.png',
    name: 'Снежинка золотая',
    count: '12',
    year: '2020',
    shape: 'снежинка',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 40
  },
  {
    num: 'https://i.ibb.co/nwkvtpt/41.png',
    name: 'Снежинка арктическая',
    count: '11',
    year: '2020',
    shape: 'снежинка',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 41
  },
  {
    num: 'https://i.ibb.co/vZpbQyv/42.png',
    name: 'Зелёный шар',
    count: '10',
    year: '1980',
    shape: 'шар',
    color: 'зелёный',
    size: 'средний',
    favorite: false,
    id: 42
  },
  {
    num: 'https://i.ibb.co/przwZN9/43.png',
    name: 'Снежинка двухцветная',
    count: '6',
    year: '1960',
    shape: 'снежинка',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 43
  },
  {
    num: 'https://i.ibb.co/pf4753W/44.png',
    name: 'Фигурка Ангела',
    count: '11',
    year: '1940',
    shape: 'фигурка',
    color: 'красный',
    size: 'средний',
    favorite: true,
    id: 44
  },
  {
    num: 'https://i.ibb.co/LQ9FTWJ/45.png',
    name: 'Снежинка новогодняя',
    count: '1',
    year: '1980',
    shape: 'снежинка',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 45
  },
  {
    num: 'https://i.ibb.co/D8BK3LF/46.png',
    name: 'Фигурка Мухомор',
    count: '10',
    year: '1950',
    shape: 'фигурка',
    color: 'красный',
    size: 'малый',
    favorite: false,
    id: 46
  },
  {
    num: 'https://i.ibb.co/hf81Hr8/47.png',
    name: 'Фигурка Колодец',
    count: '6',
    year: '1950',
    shape: 'фигурка',
    color: 'красный',
    size: 'малый',
    favorite: false,
    id: 47
  },
  {
    num: 'https://i.ibb.co/b7KfmZ7/48.png',
    name: 'Желтый шар с бантом',
    count: '6',
    year: '1960',
    shape: 'шар',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 48
  },
  {
    num: 'https://i.ibb.co/X3szLt1/49.png',
    name: 'Снежинка с бирюзой',
    count: '4',
    year: '1980',
    shape: 'снежинка',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 49
  },
  {
    num: 'https://i.ibb.co/S7JYV5R/50.png',
    name: 'Колокольчик большой',
    count: '3',
    year: '2020',
    shape: 'колокольчик',
    color: 'красный',
    size: 'большой',
    favorite: false,
    id: 50
  },
  {
    num: 'https://i.ibb.co/0q8yhTh/51.png',
    name: 'Шишка с изморозью',
    count: '12',
    year: '1970',
    shape: 'шишка',
    color: 'красный',
    size: 'малый',
    favorite: false,
    id: 51
  },
  {
    num: 'https://i.ibb.co/wykXPKK/52.png',
    name: 'Красный шар с надписью',
    count: '12',
    year: '1990',
    shape: 'шар',
    color: 'красный',
    size: 'большой',
    favorite: true,
    id: 52
  },
  {
    num: 'https://i.ibb.co/jb3V8Kx/53.png',
    name: 'Снежинка серебристая',
    count: '6',
    year: '2020',
    shape: 'снежинка',
    color: 'белый',
    size: 'большой',
    favorite: false,
    id: 53
  },
  {
    num: 'https://i.ibb.co/CsVjgCG/54.png',
    name: 'Зелёный шар с рисунком',
    count: '6',
    year: '2010',
    shape: 'шар',
    color: 'зелёный',
    size: 'большой',
    favorite: false,
    id: 54
  },
  {
    num: 'https://i.ibb.co/jkwLJnY/55.png',
    name: 'Пряничный домик',
    count: '1',
    year: '1940',
    shape: 'фигурка',
    color: 'желтый',
    size: 'большой',
    favorite: false,
    id: 55
  },
  {
    num: 'https://i.ibb.co/jRrYMWw/56.png',
    name: 'Пряничный теремок',
    count: '1',
    year: '1940',
    shape: 'фигурка',
    color: 'желтый',
    size: 'малый',
    favorite: false,
    id: 56
  },
  {
    num: 'https://i.ibb.co/9GFzq7m/57.png',
    name: 'Пряничная избушка',
    count: '1',
    year: '1940',
    shape: 'фигурка',
    color: 'желтый',
    size: 'средний',
    favorite: false,
    id: 57
  },
  {
    num: 'https://i.ibb.co/4Z8QJtR/58.png',
    name: 'Фигурка белого медведя',
    count: '2',
    year: '1980',
    shape: 'фигурка',
    color: 'белый',
    size: 'средний',
    favorite: false,
    id: 58
  },
  {
    num: 'https://i.ibb.co/JnCFn60/59.png',
    name: 'Желтый шар с надписью',
    count: '10',
    year: '1990',
    shape: 'шар',
    color: 'желтый',
    size: 'средний',
    favorite: false,
    id: 59
  },
  {
    num: 'https://i.ibb.co/D9sB8d6/60.png',
    name: 'Фигурка Голубь',
    count: '12',
    year: '1940',
    shape: 'фигурка',
    color: 'белый',
    size: 'средний',
    favorite: true,
    id: 60
  },
];

export default data;